package script.utilities;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

import org.dreambot.api.methods.Calculations;


public class id {
	public static final int cammyTele = 8010;
	public static final int houseTele = 8013;
	public static final int lumbridgeTele = 8008;
	public static final int fallyTele = 8009;
	public static final int varrockTele = 8007;
	public static final int rope = 954;
	public static final int litCandle = 33;
	public static final int unlitCandle = 36;
	public static final int glassblowingPipe = 1785;
	public static final int moltenGlass = 1775;
	public static final int emptyCandleLantern = 4527;
	public static final int unlitCandleLantern = 4529;
	public static final int litCandleLantern = 4531;
	public static final int vial = 229;
	public static final int fireRune = 554;
	public static final int waterRune = 555;
	public static final int airRune = 556;
	public static final int earthRune = 557;
	public static final int mindRune = 558;
	public static final int chaosRune = 562;
	public static final int deathRune = 560;
	public static final int natureRune = 561;
	public static final int lawRune = 563;
	public static final int spade = 952;
	public static final int bucket = 1925;
	public static final int pureEss = 7936;
	public static final int barcrawlCard = 455;
	public static final int rawRat = 2134;
	public static final int rawBear = 2136;
	public static final int rawChikken = 2138;
	public static final int rawBeef = 2132;
	public static final int grimyGuam = 199;
	public static final int guamUnf = 91;
	public static final int guam = 249;
	public static final int ranarr = 257;
	public static final int ranarrUnf = 99;
	public static final int grimyHarra = 205;
	public static final int harra = 255;
	public static final int harraUnf = 97;
	public static final int combatPot3 = 9741;
	public static final int goatHornDust = 9736;
	public static final int avantoe = 261;
	public static final int avantoeUnf = 103;
	public static final int irit = 259;
	public static final int iritUnf = 101;
	public static final int grimyIrit = 209;
	public static final int toadflax = 2998;
	public static final int toadflaxUnf = 3002;
	public static final int toadflaxGrimy = 3049;
	public static final int kwuarm = 263;
	public static final int kwuarmUnf = 105;
	public static final int kwuarmGrimy = 213;
	public static final int snapdragon = 3000;
	public static final int snapdragonUnf = 3004;
	public static final int snapdragonGrimy = 3051;
	public static final int cadantine = 265;
	public static final int cadantineUnf = 107;
	public static final int cadantineGrimy = 215;
	public static final int lantadyme = 2481;
	public static final int lantadymeUnf = 2483;
	public static final int lantadymeGrimy = 2485;
	public static final int dwarfweed = 267;
	public static final int dwarfweedUnf = 109;
	public static final int dwarfweedGrimy = 217;
	public static final int adamantCrossbow = 9183;
	public static final int runeCrossbow = 9185;
	public static final int diamondBoltsE = 9243;
	public static final int swampTar = 1939;
	public static final int plank = 960;
	public static final int steelNails = 1539;
	public static final int bronzeSword = 1277;
	public static final int lighthouseKey = 3848;
	public static final int summerPie = 7218;
	public static final int summerPie1_2 = 7220;
	public static final int rustyCasket = 3849;
	public static final int damagedZamorakBook = 3841;
	public static final int damagedArmadylBook = 12609;
	public static final int armaPage1 = 12617;
	public static final int armaPage2 = 12618;
	public static final int armaPage3 = 12619;
	public static final int armaPage4 = 12620;
	public static final int steelKnife = 865;
	
	
	public static final int torstol = 269;
	public static final int torstolUnf = 111;
	public static final int torstolGrimy = 219;
	public static final int attPot3 = 121;
	public static final int eyeOfNewt = 221;
	public static final int enchantedRat = 523;
	public static final int enchantedBear = 524;
	public static final int enchantedChikken = 525;
	public static final int enchantedBeef = 522;
	
	public static final int lumberyardTele = 12642;
	public static final int prayPot1 = 143;
	public static final int prayPot2 = 141;
	public static final int prayPot3 = 139;
	public static final int prayPot4 = 2434;
	public static List<Integer> prayPots = new ArrayList<Integer>();
	public static final int superAtt1 = 149;
	public static final int superAtt2 = 147;
	public static final int superAtt3 = 145;
	public static final int superAtt4 = 2436;
	public static List<Integer> superAtts = new ArrayList<Integer>();
	public static final int superStr1 = 161;
	public static final int superStr2 = 159;
	public static final int superStr3 = 157;
	public static final int superStr4 = 2440;
	public static List<Integer> superStrs = new ArrayList<Integer>();
	public static final int superCombat1 = 12701;
	public static final int superCombat2 = 12699;
	public static final int superCombat3 = 12697;
	public static final int superCombat4 = 12695;
	public static List<Integer> superCombats = new ArrayList<Integer>();
	public static final int antidote1 = 5958;
	public static final int antidote2 = 5956;
	public static final int antidote3 = 5954;
	public static final int antidote4 = 5952;
	public static List<Integer> antidotes = new ArrayList<Integer>();
	public static final int stamina4 = 12625;
	public static final int stamina3 = 12627;
	public static final int stamina2 = 12629;
	public static final int stamina1 = 12631;
	public static List<Integer> staminas = new ArrayList<Integer>();
	public static final int bass = 365;
	public static final int monkfish = 7946;
	public static final int swordfish = 373;
	public static final int pineapplePizza1 = 2303;
	public static final int pineapplePizza2 = 2301;
	public static final int seaTurtle = 397;
	public static final int casket = 405;
	
	public static final int runeDaggerPP = 5678;
	public static final int runeSword = 1289;
	public static final int blueDhideBody = 2499;
	public static final int earthBattlestaff = 1399;
	public static final int runeDagger = 1213;
	public static final int redDhideBody = 2501;
	public static final int adamantPlatebody = 1123;
	public static final int runeAxe = 1359;
	public static final int greenDhideBody = 1135;
	public static final int onyxBoltsE = 9245;
	public static final int mithrilPlatebody = 1121;
	public static final int rune2h = 1319;
	public static final int redDhideBodyG = 12327;
	public static final int redDhideChaps = 2495;
	public static final int blackDhideBody = 2503;
	public static final int redDhidevambs = 2489;
	public static final int mysticEarthStaff = 1407;
	public static final int initiateSallet = 5574;
	public static final int proselyteTasset = 9678;
	public static final int runePlateskirt = 1093;
	public static final int saradominPlateskirt = 3479;
	public static final int runeBattleaxe = 1373;
	public static final int runeMedHelm = 1147;
	public static final int mithrilSword = 1285;
	
	public static final int staffOfAir = 1381;
	public static final int staffOfEarth = 1385;
	public static final int staffOfWater = 1383;
	public static final int staffOfFire = 1387;
	
	public static final int magicLongbow = 859;
	public static final int yewLongbow = 855;
	

	public static final int rawShark = 383;
	public static final int giantFrogLegs = 4518;
	public static final int bloodRune = 565;
	public static final int cosmicRune = 564;
	public static final int knife = 946;
	public static final int saradominCape = 2412;
	public static final int zamorakCape = 2414;
	public static final int guthixCape = 2413;
	public static final int saradominStaff = 2415;
	public static final int zamorakStaff = 2417;
	public static final int guthixStaff = 2416;
	public static final int eventRPG = 12727;
	public static final int fremmy_beerTankard = 3803;
	public static final int fremmy_kegOfBeer = 3711;
	public static final int tinderbox = 590;
	public static final int fremmy_huntersTalisman = 3697;
	public static final int fremmy_huntersTalismanAbsorbedDraugen = 3696;
	public static final int fremmy_lowAlcoholKeg = 3712;
	public static final int fremmy_lyre = 3689;
	public static final int fremmy_enchantedLyre = 3690;
	public static final int fremmy_strangeObject1 = 3713;
	public static final int fremmy_strangeObject2 = 3714;
	public static final int fremmy_askeladdenPromise = 3709;
	public static final int fremmy_legendaryCocktail = 3707;
	public static final int fremmy_championsToken = 3706;
	public static final int fremmy_warriorsContract = 3710;
	public static final int fremmy_weatherForecast = 3705;
	public static final int fremmy_seaFishingMap = 3704;
	public static final int fremmy_unusualFish = 3703;
	public static final int fremmy_customBowString = 3702;
	public static final int fremmy_trackingMap = 3701;
	public static final int fremmy_fiscalStatement = 3708;
	public static final int fremmy_customBoots = 3700;
	public static final int fremmy_fremennikBallad = 3699;
	public static final int fremmy_exoticFlowers = 3698;
	public static final int fremmy_redHerring = 3742;
	public static final int fremmy_emptyJug = 3732;
	public static final int fremmy_woodenDisk = 3744;
	public static final int fremmy_oldRedDisk = 9947;
	public static final int fremmy_emptyBucket = 3727;
	public static final int fremmy_redGoop = 3746;
	public static final int fremmy_redDisk = 3743;
	public static final int fremmy_vaseLid = 3737;
	public static final int fremmy_fullBucket = 3722;
	public static final int fremmy_fullJug = 3729;
	public static final int fremmy_2_5Bucket = 3725;
	public static final int fremmy_2_3Jug = 3730;
	public static final int fremmy_4_5Bucket = 3723;
	public static final int fremmy_vase = 3734;
	public static final int fremmy_fullVase = 3735;
	public static final int fremmy_wholeVase = 3740;
	public static final int fremmy_frozenKey = 3741;
	public static final int fremmy_unfrozenKey = 3745;
	public static final int jugOfWine = 1993;
	public static final int jug = 1935;
	public static final int rangePot4 = 2444;
	public static final int rangePot3 = 169;
	public static final int rangePot2 = 171;
	public static final int rangePot1 = 173;
	public static List<Integer> rangedPots = new ArrayList<Integer>();
	public static List<Integer> randCapes = new ArrayList<Integer>();
	public static final int dorgBow = 8880;
    public static final int boneBolts = 8882;

	public static final int zamorakCoif = 10374;
	public static final int snakeskinBandana = 6326;
	public static final int coif = 1169;
	public static final int cowl = 1167;
    public static final int blackBody = 2503;
	public static final int redBody = 2501;
	public static final int blueBody = 2499;
	public static final int snakeskinBody = 6322;
	public static final int studdedBody = 1133;
	public static final int hardLeatherBody = 1131;
	public static final int leatherBody = 1129;
    public static final int blackLegs = 2497;
	public static final int redLegs = 2495;
	public static final int blueLegs = 2493;
	public static final int snakeskinChaps = 6324;
	public static final int studdedChaps = 1097;
	public static final int leatherChaps = 1095;
	public static final int darkRedCape = 4397;
	public static final int lightRedCape = 4317;
	public static final int yellowCape = 4337;
	public static final int lightBlueCape = 4357;
	public static final int lightGreenCape = 4377;
	public static int randCape = 0;
	public static final int avasAccumulator	= 10499;
	public static final int snakeskinBoots = 6328;
	public static final int leatherBoots = 1061;
	public static final int guthixBracers = 10376;
	public static final int blueVambs = 2487;
	public static final int redVambs = 2489;
	public static final int greenVambs = 1065;
	public static final int bookOfLaw = 12610;
	public static final int blackShield = 22284;
	public static final int redShield = 22281;
	public static final int blueShield = 22278;
	public static final int greenShield = 22275;
	public static final int snakeskinShield = 22272;
	public static final int hardleatherShield = 22269;
	public static final int woodenShield = 1171;
    public static final int ironDart = 807;
	public static final int steelDart = 808;
	public static final int mithDart = 809;
	public static final int addyDart = 810;
	public static final int grimyRanarr = 207;
	public static final int grimyAvantoe = 211;
	public static final int grimyKwuarm = 213;
	public static final int grimyCadantine = 215;
	public static final int grimyLantadyme = 2485;
	public static final int silverSickle = 2961;
	public static final int blessedSickle = 2963;
	public static final int salveGraveyardTab = 19619;
	public static final int druidPouch = 2957;
	public static final int druidPouchFilled = 2958;

	public static final int pieDish = 2313;
	public static final int applePie1_2 = 2335;
	public static final int applePie = 2323;
	public static final int meatPie1_2 = 2331;
	public static final int meatPie = 2327;
	public static final int mortFungus = 2970;
	public static final int rottenFood = 2959;
	public static final int natureSpirit_mirror = 2966;
	public static final int natureSpirit_fillimansDiary = 2967;
	public static final int natureSpirit_usedSpell = 2969;
	public static final int natureSpirit_spell = 2968;
	public static final int natureSpirit_washingBowl = 2964;
	public static final int pot = 1931;
	public static final int dBones = 536;
	public static final int draynorTab = 19615;
	public static final int fenkensteinTab = 19621;
	public static final int polishedButtons = 10496;
	public static final int ironBar = 2351;
	public static final int ectotokens = 4278;
	public static final int holySymbol = 1718;
	public static final int hardLeather = 1743;
	public static final int bucketOfSlime = 4286;
	public static final int potOfDBones = 4261;
	public static final int hammer = 2347;
	public static final int undeadChicken = 10487;
	public static final int barMagnet = 10489;
	public static final int selectedIron = 10488;
	public static final int blessedAxe = 10491;
	public static final int undeadTwigs = 10490;
	public static final int researchNotes = 10492;
	public static final int translatedNotes = 10493;
	public static final int aPattern = 10494;
	public static final int snapdragonSeed = 5300;
	public static final int ranarrSeed = 5295;
	public static final int torstolSeed = 5304;
	public static final int toadflaxSeed = 5296;
	public static final int snapegrassSeed = 22879;
	public static final int giantKey = 20754;
	public static final int bigBones = 532;
	public static final int steelArrow = 886;
	
	public static final int ironBoots = 4121;
	
	public static final int ensouledKalphiteHead1 = 13489;
	public static final int ensouledKalphiteHead2 = 13490;
	
	public static final int mithBolts = 9142;
	public static final int fireBattlestaff = 1393;
	public static final int airBattlestaff = 1397;
	public static final int waterBattlestaff = 1395;
	
	public static final int shieldLeftHalf = 2366;
	public static final int dragonSpear = 1249;
	public static final int runeSpear = 1247;
	public static final int keyLoopHalf = 987;
	public static final int keyToothHalf = 985;
	public static final int uncutDiamond = 1617;
	
	public static final int fireTalisman = 1442;
	
	public static final int blackRobe = 581;
	public static final int xericianTop = 13387;
	public static final int robeTopOfDarkness = 20131;
	public static final int ironAxe = 1349;
	public static final int steelAxe = 1353;
	public static final int blackAxe = 1361;
	public static final int mithAxe = 1355;
	public static final int addyAxe = 1357;
	public static final int oakLogs = 1521;
	public static final int logs = 1511;
	public static final int guthixCloak = 10448;
	public static final int mysticBoots = 4097;
	public static final int blueBoots = 630;
	public static final int ancientMitre = 12203;
	public static final int hoodOfDarkness = 20128;
	public static final int creamHat = 662;
	public static final int robeBottomOfDarkness = 20137;
	public static final int xericianRobe = 13389;
	public static final int zamorakMonkBottom = 1033;

	public static final int occultNecklace = 20137;
	
	public static final int dragonMedHelm = 1149;
	public static final int runeFullHelm = 1163;
	public static final int addyFullHelm = 1161;
	public static final int mithFullHelm = 1159;
	public static final int steelFullHelm = 1157;
	public static final int ironFullHelm = 1153;
	public static final int runePlatelegs = 1079;
	public static final int addyPlatelegs = 1073;
	public static final int mithPlatelegs = 1071;
	public static final int steelPlatelegs = 1069;
	public static final int ironPlatelegs = 1067;
	public static final int runeChainbody = 1113;
	public static final int addyPlatebody = 1123;
	public static final int mithPlatebody = 1121;
	public static final int steelPlatebody = 1119;
	public static final int ironPlatebody = 1115;
	public static final int dragonBoots = 11840;
	public static final int runeBoots = 4131;
	public static final int addyBoots = 4129;
	public static final int runeKiteshield = 1201;
	public static final int addyKiteshield = 1199;
	public static final int mithKiteshield = 1197;
	public static final int steelKiteshield = 1193;
	public static final int ironKiteshield = 1191;
    public static final int brineSabre = 11037;
	public static final int addyScimmy = 1331;
	public static final int mithScimmy = 1329;
	public static final int steelScimmy = 1325;
	public static final int bodyTalisman = 1446;
	public static final int ironScimmy = 1323;
	public static final int markOfGrace = 11849;
	
	public static LinkedHashMap<Integer, Integer> approvedAlchs = new LinkedHashMap<Integer,Integer>();
	public static List<Integer> needAtLeast1Alchs = new ArrayList<Integer>();
	public static LinkedHashMap<Integer, Integer> xpAlchs = new LinkedHashMap<Integer,Integer>();
	public static List<Integer> allAlchs = new ArrayList<Integer>();
	public static void initializeIDLists()
	{
		xpAlchs.put(magicLongbow,18000);
		xpAlchs.put(yewLongbow,18000);
		
		approvedAlchs.put(redDhideBodyG,8);
		approvedAlchs.put(redDhideChaps,65);
		needAtLeast1Alchs.add(redDhideChaps);
		approvedAlchs.put(blackDhideBody,65);
		needAtLeast1Alchs.add(blackDhideBody);
		approvedAlchs.put(redDhidevambs,65);
		needAtLeast1Alchs.add(redDhidevambs);
		approvedAlchs.put(mysticEarthStaff,18000);
		approvedAlchs.put(initiateSallet,125);
		approvedAlchs.put(proselyteTasset,70);
		approvedAlchs.put(runePlateskirt,70);
		approvedAlchs.put(saradominPlateskirt,8);
		approvedAlchs.put(runeBattleaxe,70);
		approvedAlchs.put(runeMedHelm,70);
		approvedAlchs.put(mithrilSword,125);
		approvedAlchs.put(runeDaggerPP,70);
		approvedAlchs.put(runeSword,70);
		approvedAlchs.put(blueDhideBody,120);
		needAtLeast1Alchs.add(blueDhideBody);
		approvedAlchs.put(earthBattlestaff,18000);
		approvedAlchs.put(runeDagger,70);
		approvedAlchs.put(redDhideBody,65);
		needAtLeast1Alchs.add(redDhideBody);
		approvedAlchs.put(adamantPlatebody,120);
		needAtLeast1Alchs.add(adamantPlatebody);
		approvedAlchs.put(runeAxe,35);
		needAtLeast1Alchs.add(runeAxe);
		approvedAlchs.put(greenDhideBody,120);
		needAtLeast1Alchs.add(greenDhideBody);
		approvedAlchs.put(onyxBoltsE,11000);
		approvedAlchs.put(mithrilPlatebody,120);
		needAtLeast1Alchs.add(mithrilPlatebody);
		approvedAlchs.put(rune2h,70);
		
		for(Integer i : xpAlchs.keySet())
		{
			allAlchs.add(i);
		}
		for(Integer i : approvedAlchs.keySet())
		{
			allAlchs.add(i);
		}
		
		prayPots.add(prayPot1);
		prayPots.add(prayPot2);
		prayPots.add(prayPot3);
		prayPots.add(prayPot4);
		superAtts.add(superAtt1);
		superAtts.add(superAtt2);
		superAtts.add(superAtt3);
		superAtts.add(superAtt4);
		superStrs.add(superStr1);
		superStrs.add(superStr2);
		superStrs.add(superStr3);
		superStrs.add(superStr4);
		superCombats.add(superCombat1);
		superCombats.add(superCombat2);
		superCombats.add(superCombat3);
		superCombats.add(superCombat4);
		staminas.add(stamina1);
		staminas.add(stamina2);
		staminas.add(stamina3);
		staminas.add(stamina4);
		antidotes.add(antidote1);
		antidotes.add(antidote2);
		antidotes.add(antidote3);
		antidotes.add(antidote4);
		int tmp = (int) Calculations.nextGaussianRandom(10, 5);
        if(tmp > 15) randCape = darkRedCape;
        if(tmp > 12) randCape = lightRedCape;
        if(tmp > 10) randCape = yellowCape;
        if(tmp > 8) randCape = lightGreenCape;
        if(randCape == 0) randCape = lightBlueCape;

        
        randCapes.add(darkRedCape);
        randCapes.add(lightRedCape);
        randCapes.add(yellowCape);
        randCapes.add(lightGreenCape);
        randCapes.add(lightBlueCape);
        rangedPots.add(rangePot1);
        rangedPots.add(rangePot2);
        rangedPots.add(rangePot3);
        rangedPots.add(rangePot4);
	}
}
